---
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: "remove any old docker components"
    become: yes
    apt:
      name: ["docker.io", "docker-engine", "containerd", "runc"]
      state: absent

  - name: "install requirements for app and docker"
    become: yes
    apt:
      name: ["python3-pip", "python3-kubernetes", "git", "python3-flask", "ca-certificates", "curl", "gnupg", "lsb-release"]
      state: latest
      update_cache: yes

  - name: Add Docker GPG apt Key
    become: yes
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    become: yes
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Update apt and install docker-ce
    become: yes
    apt: 
      update_cache: yes
      name: ["docker-ce", "docker-ce-cli", "containerd.io"] 
      state: latest

  - name: "copy scripts over to server"
    become: yes
    copy:
      src: ~/project/scripts/archive.tar.gz
      dest: ~/home/ubuntu/project/archive.tar.gz