---
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: "remove any old docker components"
    become: yes
    apt:
      name: ["docker.io", "docker-engine", "containerd", "runc"]
      state: absent

  - name: "install requirements for app and docker"
    become: yes
    apt:
      name: ["python3-pip", "python3-kubernetes", "kubernetes", "git", "python3-flask", "ca-certificates", "curl", "gnupg", "lsb-release", "python3-venv"]
      state: latest
      update_cache: yes

  - name: Add Docker GPG apt Key
    become: yes
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    become: yes
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Update apt and install docker-ce
    become: yes
    apt: 
      update_cache: yes
      name: ["docker-ce", "docker-ce-cli", "containerd.io"] 
      state: latest

  - name: "copy Makefile to server"
    become: yes
    copy:
      src: ~/project/scripts/Makefile
      dest: /home/ubuntu/
      owner: ubuntu
      group: ubuntu
      mode: 0777

  - name: "copy Dockerfile to server"
    become: yes
    copy:
      src: ~/project/scripts/Dockerfile
      dest: /home/ubuntu/
      owner: ubuntu
      group: ubuntu
      mode: 0777

  - name: "copy requirements to server"
    become: yes
    copy:
      src: ~/project/scripts/requirements.txt
      dest: /home/ubuntu/
      owner: ubuntu
      group: ubuntu
      mode: 0777

  - name: "copy rundocker to server"
    become: yes
    copy:
      src: ~/project/scripts/rundocker.sh
      dest: /home/ubuntu/
      owner: ubuntu
      group: ubuntu
      mode: 0777

  - name: "copy dockerpush to server"
    become: yes
    copy:
      src: ~/project/scripts/docker_push.sh
      dest: /home/ubuntu/
      owner: ubuntu
      group: ubuntu
      mode: 0777

  - name: "copy kubernetesdeploy to server"
    become: yes
    copy:
      src: ~/project/scripts/kubernetesDeploy.sh
      dest: /home/ubuntu/
      owner: ubuntu
      group: ubuntu
      mode: 0777

  - name: "copy cryptotest to server"
    become: yes
    copy:
      src: ~/project/scripts/cryptotest.py
      dest: /home/ubuntu/
      owner: ubuntu
      group: ubuntu
      mode: 0777

  - name: "copy config.txt to server"
    become: yes
    copy:
      src: ~/project/scripts/config.txt
      dest: /home/ubuntu/
      owner: ubuntu
      group: ubuntu
      mode: 0777

  - name: "copy app.py to server"
    become: yes
    copy:
      src: ~/project/scripts/app.py
      dest: /home/ubuntu/
      owner: ubuntu
      group: ubuntu
      mode: 0777

  - name: "copy deployGreenApp.sh to server"
    become: yes
    copy:
      src: ~/project/scripts/deployGreenApp.sh
      dest: /home/ubuntu/
      owner: ubuntu
      group: ubuntu
      mode: 0777
      
  - name: "copy delete_green_app.sh to server"
    become: yes
    copy:
      src: ~/project/scripts/delete_green_app.sh
      dest: /home/ubuntu/
      owner: ubuntu
      group: ubuntu
      mode: 0777

  - name: "copy kubernetesDeploy.sh to server"
    become: yes
    copy:
      src: ~/project/scripts/kubernetesDeploy.sh
      dest: /home/ubuntu/
      owner: ubuntu
      group: ubuntu
      mode: 0777

  - name: "verify file"
    become: yes
    raw: ls -la && ls -la /home/ubuntu/