---
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: "install flask"
    become: yes
    apt:
      name: ["python3-pip", "docker.io", "python3-kubernetes", "git", "python3-flask"]
      state: latest
      update_cache: yes
