---
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: "install nginx"
    become: yes
    apt:
      name: ["nginx", "git", ]
      state: latest
      update_cache: yes
