#FROM python:3.9.7-buster
FROM ubuntu/nginx:1.18-21.10_beta
#FROM nginx

## Step 1:
# Create a working directory
WORKDIR /app

## Step 2:
# Copy source code to working directory
COPY . cryptotest.py /app/

COPY results.txt /usr/www/inex.html
## Step 3:
# Install packages from requirements.txt
# hadolint ignore=DL3013
RUN pip install --upgrade pip &&\
    pip install --no-cache-dir --trusted-host pypi.python.org -r requirements.txt

## Step 4:
# Expose port 80
EXPOSE 80

## Step 5:
# Run app.py at container launch
#CMD ["python", "app.py"]
CMD ["python", "cryptotest.py"]

