---
  - name: "install Docker components"
    become: yes
    apt:
      name: ["python3-pip", "docker.io", "python3-kubernetes", "git", "python3-flask"]
      state: latest
      update_cache: yes

#   - name: Add Docker GPG apt Key
#     apt_key:
#       url: https://download.docker.com/linux/ubuntu/gpg
#       state: present

#   - name: Add Docker Repository
#     apt_repository:
#       repo: deb https://download.docker.com/linux/ubuntu xenial stable
#       state: present

#   - name: Update apt and install docker-ce
#     apt: update_cache=yes name=docker-ce state=latest

  - name: Install Docker Module for Python
    pip:
      name: docker

  - name: Pull default Docker image
    docker_image:
        name: poroko/flask-demo-app
        source: pull  