---
#   - name: "install Docker components"
#     become: yes
#     apt:
#       name: ["python3-pip", "docker.io", "python3-kubernetes", "git", "python3-flask"]
#       state: latest
#       update_cache: yes

    - name: Extract archive.tar.gz
      become: yes
      unarchive:
        src: /home/ubuntu/archive.tar.gz
        dest: /home/ubuntu/

    - name: Test for file
      become: yes
      raw: ls -la
      
    - make:
        chdir: /home/ubuntu/
        target: setup
        file: /home/ubuntu/Makefile
      become: yes
