---
#   - name: "install Docker components"
#     become: yes
#     apt:
#       name: ["python3-pip", "docker.io", "python3-kubernetes", "git", "python3-flask"]
#       state: latest
#       update_cache: yes
  - name: "execute make dockerfile"
    become: yes
    command: |
        pwd && ls -la && ls -la ../
        make setup
        make install
        make lint
        make dockerflask