---
#   - name: "install Docker components"
#     become: yes
#     apt:
#       name: ["python3-pip", "docker.io", "python3-kubernetes", "git", "python3-flask"]
#       state: latest
#       update_cache: yes

    - name: Extract archive.tar.gz
      unarchive:
        src: /home/ubuntu/archive.tar.gz
        dest: /home/ubuntu/

    - name: Make test
    - make:
        target: setup
      become: yes
