---
    - make:
        chdir: /home/ubuntu/
        target: setup
        file: /home/ubuntu/Makefile
      become: yes
      
    - make:
        chdir: /home/ubuntu/
        target: install
        file: /home/ubuntu/Makefile
      become: yes
