---
#   - name: "install Docker components"
#     become: yes
#     apt:
#       name: ["python3-pip", "docker.io", "python3-kubernetes", "git", "python3-flask"]
#       state: latest
#       update_cache: yes
  - name: "execute make dockerfile"
  - restore_cache:
        keys: [crypto-app]
    become: yes
    working_directory: ~/project/scripts
    command: |
        make setup
        make install
        make lint
        make dockerflask