---
#   - name: "install Docker components"
#     become: yes
#     apt:
#       name: ["python3-pip", "docker.io", "python3-kubernetes", "git", "python3-flask"]
#       state: latest
#       update_cache: yes

        - name: "restore cache"
        - restore_cache:
            keys: [crypto-app]

        - name: "execute make scripts"
          become: yes
          command: |
            cd ~/project/scripts/
            ls -la
            # make setup
            # make install
            # make lint
            # make dockerflask