---
#   - name: "install Docker components"
#     become: yes
#     apt:
#       name: ["python3-pip", "docker.io", "python3-kubernetes", "git", "python3-flask"]
#       state: latest
#       update_cache: yes

        - name: "execute make scripts"
          become: yes
          command: |
            ls -la
            cd /home/ubuntu/
            tar -zxvf archive.tar.gz 
            ls -la
